### ISSUE TITLE
Warnings produced when sending queries

### ISSUE THREAD

**Issue by chamaoskurumi** [INWTlab/dbtools#76]
### Problem

Using `dbtools` under newer R Versions such as 4.4.1 often (usually when using `dbtools::sendQuery()`) produces the two following warnings:
* **Unsigned INTEGER in col ... imported as numeric**
* **Decimal MySQL column ... imported as numeric**

Here two log excerpts how the warnings arise:
```
...
   29. │                             ├─dbtools (local) FUN(X[[i]], ...)
   30. │                             └─dbtools (local) FUN(X[[i]], ...)
   31. │                               ├─DBI::dbSendQuery(db, query)
   32. │                               └─RMySQL::dbSendQuery(db, query)
   33. │                                 └─RMySQL (local) .local(conn, statement, ...)
   34. └─base::unlist(.)

 Unsigned INTEGER in col 1 imported as numeric
```

```
    7.     ├─dbtools::sendQuery(...)
    8.     └─dbtools::sendQuery(...)
    9.       ├─dbtools::sendQuery(db, SingleQueryList(as.list(query)), ...)
   10.       └─dbtools::sendQuery(db, SingleQueryList(as.list(query)), ...)
   11.         └─dbtools (local) .local(db, query, ...)
   12.           └─dbtools::reTry(...)
   13.             ├─base::try(fun(...), silent = TRUE)
   14.             │ └─base::tryCatch(...)
   15.             │   └─base (local) tryCatchList(expr, classes, parentenv, handlers)
   16.             │     └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
   17.             │       └─base (local) doTryCatch(return(expr), name, parentenv, handler)
   18.             └─dbtools (local) fun(...)
   19.               └─base::lapply(query, sendQuery, db = con, ...)
   20.                 ├─dbtools (local) FUN(X[[i]], ...)
   21.                 └─dbtools (local) FUN(X[[i]], ...)
   22.                   ├─DBI::dbSendQuery(db, query)
   23.                   └─RMySQL::dbSendQuery(db, query)
   24.                     └─RMySQL (local) .local(conn, statement, ...)

Decimal MySQL column 22 imported as numeric

```

### Possible solutions

I have no easy regex at hand, the existing tests in the package do not produce these warnings.

As suggested [here](https://stackoverflow.com/questions/34399043/how-to-prevent-rmysql-warnings-unsigned-integer-in-col-imported-as-numeric),  a part of the solution could be "to switch from RMySQL to [RMariaDB](https://rmariadb.r-dbi.org/)".

Ultimately, the R Version in the Docker file should be updated, as has been already planned in this old PR https://github.com/INWTlab/dbtools/pull/74.

**Comment by jonathan-inwt** [comment]
> As suggested [here](https://stackoverflow.com/questions/34399043/how-to-prevent-rmysql-warnings-unsigned-integer-in-col-imported-as-numeric), a part of the solution could be "to switch from RMySQL to [RMariaDB](https://rmariadb.r-dbi.org/)".

This can easily be achieved by adjusting the credentials object.

```R
dbtools::Credentials(
    drv = dbtools::MariaDB,
    user = 'my_db_user',
    password = 'my_db_password',
    dbname = 'my_db_schema',
    host = 'my_db_host',
    port = 3306
)
```

**Comment by jonathan-inwt** [comment]
Should be resolved with https://github.com/INWTlab/dbtools/commit/e815cf10e7d344b116bc78388d40dd0d6af2631f
